### PR TITLE
Fix for Issue #158

### PR DESCRIPTION
**Pull request by tuvokki**
"Is it possible to add a callback to the resize_widget function, that is
called when the resizing of a widget is finished? This may help to
update the widget content properly."

Possible, I have made an implementation of this because I thought I wanted to use it.

### CODE REVIEW

**Comment by dustmoo** [comment]
Perfect! Thanks.

**Comment by tuvokki** [comment]
No problem.

**Comment by pttien** [comment]
hi! can you give me a code demo of resize_widget function with callback parameter,because i don't know which function is  callback parameter! 
thank!

**Comment by tuvokki** [comment]
See this JSFiddle: http://jsfiddle.net/tuvokki/zo33wzvL/ be sure to open the console to see the output.

**Pull request merged**
