### PR TITLE
Possible solution to memory leak #124

### PR DESCRIPTION
**Pull request by brokenseal**
#124

### CODE REVIEW

**Comment by ekozan** [comment]
+1 thx

**Comment by bostondevin** [comment]
I'm noticing the memory leaks too - is this project being managed? I see a bunch of open pull requests...

**Comment by 0vermind** [comment]
good question

**Comment by brokenseal** [comment]
Thanks for that!

**Comment by dustmoo** [comment]
Sure thing! I could use more of your help... keep the fixes coming. :)

**Pull request merged**
